		<link rel="stylesheet" href="css/donation-panel.css?v=<?= VERSION ?>" />
		<div id="donate-panel">
			<p>Donate in game ISK/PLEX to support development? Send to <i>Kariyo Astrien</i> in game and put "Tripwire" in the comment!<br/>
			Donate real money to pay for server hosting for public Tripwire? Click this!</p>
			<form id="donate_form" action="https://www.paypal.com/donate" method="post" target="_top">
				<input type="hidden" name="hosted_button_id" value="XDAPBTRVRL8CW" />
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
				<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
			</form>
		</div>
